---
- name: "Include set motd task RedHat"
  ansible.builtin.include_tasks: set-motd-RedHat.yml
  when: ansible_os_family == "RedHat"
- name: "Include set motd task for Debian"
  ansible.builtin.include_tasks: set-motd-Debian.yml
  when: ansible_os_family == "Debian"
