---
- name: "Include set motd task RedHat"
  include_tasks: set-motd-RedHat.yml
  when: ansible_distribution_file_variety == "RedHat"
- name: "Include set motd task for Debian"
  include_tasks: set-motd-Debian.yml
  when: ansible_distribution_file_variety == "Debian"
...
