---
name: Molecule Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
defaults:
  run:
    working-directory: 'motd'
jobs:
  molecule-check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - 3.7
          - 3.8
        distro:
          - centos8
          - centos7
          - debian9
          - debian10
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'motd'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies for debian
        if: ${{ matrix.distro == 'debian9' || matrix.distro == 'debian10' }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible molecule[docker] docker
      
      - name: Install dependencies for centos
        if: ${{ matrix.distro == 'centos7' || matrix.distro == 'centos8' }}
        run: |
          sudo mkdir -p /etc/ssh
          sudo touch /etc/ssh/sshd_config
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible molecule[docker] docker
      - name: Test with molecule
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
        run: molecule test
